server:
  port: 8080

spring:
  application:
    name: server-primary
  datasource:

    url: jdbc:h2:file:./db_primaria
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # Cria a tabela do User automaticamente
    show-sql: true     # Mostra o insert no terminal (bom para o professor ver)