# Configuração do Servidor
server.port=8081
spring.application.name=server-replica1

# Configuração do Banco de Dados H2 (Arquivo Local)
spring.datasource.url=jdbc:h2:file:./db_replica1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true